add_newline = false
command_timeout = 1000
continuation_prompt = '▶▶ '

format = """\
[󰀵 ](fg:#897EE3)\
$directory\
$character\
"""

right_format = """
$kubernetes\
$battery\
"""


[kubernetes]
format = '[☸ $context \($namespace\)](#524B88) '
disabled = true

[[battery.display]]
threshold = 5
style = 'bold red'

[[battery.display]]
threshold = 20
style = 'bold yellow'

[character]
# vicmd_symbol = "[](bold green)"
vimcmd_symbol = '[V](bold green) '
success_symbol = "[❯](fg:#03DAC6)"
error_symbol = "[❯](fg:#FF3A39)"

[directory]
truncation_length = 2
# truncation_symbol = " ~/…/"
fish_style_pwd_dir_length=3
read_only_style = '197'
read_only = '  '
style = "blue bold"
home_symbol = " ~"
truncate_to_repo = false


[package]
disabled = true

[username]
disabled = true

[hostname]
disabled = true

[aws]
disabled = true

[docker_context]
disabled = true

[git_branch]
disabled = true

[git_commit]
disabled = true

[git_state]
disabled = true

[git_metrics]
disabled = true

[git_status]
disabled = true

[vagrant]
disabled = true
